<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9iNnm4W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9iNnm4W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9iNnm4W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9iNnm4W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9iNnm4W\App_KernelDevDebugContainer([
    'container.build_hash' => '9iNnm4W',
    'container.build_id' => '3cd78f5d',
    'container.build_time' => 1666708046,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9iNnm4W');
