<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFHyheYL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFHyheYL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFHyheYL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFHyheYL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFHyheYL\App_KernelDevDebugContainer([
    'container.build_hash' => 'FHyheYL',
    'container.build_id' => 'be0182d3',
    'container.build_time' => 1670167418,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFHyheYL');
